### ISSUE TITLE
Crossbows created with Silent Gear don't function with Infinity (but can be enchanted)

### ISSUE THREAD

**Issue by katubug** [Fuzss/sneakycurses#1]
Hi! Pretty much what the title says. A player on my server enchanted their Silent Gear crossbow with Infinity via the enchanting table, but arrows are still consumed (and the crossbow won't function without an arrow). I have tested and everything works as expected with the vanilla crossbow.

My guess is that due to the different item ID, the enchantment applies but doesn't function. If this would be fixable (either by adding Infinity functionality to the SG crossbows, or exempting them from receiving the enchant), that would be rad! Thanks very much for your time! :D

Minecraft: 1.15.2
Forge: 31.2.31
Sneaky Magic: 2.0
Silent Gear: 1.11.0-143

**Comment by Fuzss** [comment]
Can't fix, as in contrast to vanilla bows the vanilla crossbow isn't implemented in a very generic way, so the patches in this mod easily break for modded crossbows.

**Comment by katubug** [comment]
I see, so there's also no way to prevent the enchant from being added to the modded crossbows?

**Comment by Fuzss** [comment]
The new v1.2 adds some blacklists to help with your issue.
