### ISSUE TITLE
Gameplay elements to reveal curses

### ISSUE THREAD

**Issue by Klaaf** [Fuzss/sneakycurses#15]
What would you think of adding a way for the player to permanently reveal hidden curses on an item using gameplay elements?

I was thinking, for instance:
- After using/wearing cursed equipment for a while, curses would be revealed naturally to the player
- An anvil recipe to reveal the curses maybe? Or any other workstation/interactable block. For example you could have a recipe with amethyst to identify curses in exchange for some XP

These are just some random ideas on top of my head, I thought it could be interesting. Anyways, love your mod, keep up the great work!

**Comment by Fuzss** [comment]
I like those suggestions, thanks!

It would mean the mod is not longer client-only, but I think that's ok.

**Comment by Fuzss** [comment]
Both suggestions have been implemented in v8.0.0. Thanks once again for those!
