### ISSUE TITLE
[Crash]: Crash on start-up

### ISSUE THREAD

**Issue by d-rick** [Fuzss/sneakycurses#17]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.1

### Notes (Required)

The game Crashed

### Crash Report (Required)

https://paste.ee/p/1zV2f

### latest.log (Optional)

https://paste.ee/p/VdFZB

**Comment by Fuzss** [comment]
Thanks, fixed in v8.0.2.
