### ISSUE TITLE
ALL melee attacks have "sweeping" functionality even without enchantments.

### ISSUE THREAD

**Issue by SodiumShine** [Fuzss/sneakycurses#2]
The normally sword exclusive ability to sweep attack multiple mobs in one strike gets applied to punching, hitting things with blocks, eggs, pickaxes etc.
Sweeping edge was not applied to anything when testing this.

Minecraft 1.16.5
Forge 36.0.10 (also tested with 36.0.13 if that matters)
SneakyMagic version 1.2.1

Only other mods present were JEI, and MmmMmmMmmMmm

**Comment by Fuzss** [comment]
Fixed in v1.3, now only weapons that can be enchanted with Sweeping Edge will trigger a sweep attack.
