### ISSUE TITLE
[Crash] java.util.ConcurrentModificationException: null

### ISSUE THREAD

**Issue by IdrisQe** [Fuzss/sneakycurses#3]
So I was launching a modpack I was putting together and testing but...
Well, the game crashed, and it indicated SneakyMagic (as far as I can tell, only it?) in the big list of what messed up where.
**Relevant part of the log: https://pastebin.com/qjejeB23**

And then the _Not Enough Crashes_ crash handler popped up and it looked like this:
![image](https://user-images.githubusercontent.com/40530630/108464884-d1957c00-7235-11eb-9c7c-d61672b04114.png)
Probably since it was a renderer error, or maybe it occured before the fonts were loaded in right? No idea.

Unfortunately a kinda large modlist but if anyone can explain what the issue seems to be I may be able to help pin it down to specific mod interactions.

**Comment by Fuzss** [comment]
Seems to be a bug in Sneaky Magic itself, not an incompatibility.
Does the crash occur every time you launch your pack?

**Comment by IdrisQe** [comment]
Hm... After trying a few more times, no problems arise.
However, in the time between, I had Sneaky Magic disabled in order to keep testing other things, and noticed that my Java wasn't using my dedicated GPU, but the crummy integrated one in my CPU. I'm going to test again with it set to use the integrated once more, to see if that's somehow the cause.

Edit: Nope, loaded just fine. Maybe I was doing something else at the time and ran out of RAM or something?...
Or maybe it was just some freak bit-flip from cosmic radiation! No idea honestly.

**Comment by Fuzss** [comment]
Pretty sure it's a race condition. I'll have to investigate.
Did the crash possibly occur when you loaded the mod for the very first time?

**Comment by IdrisQe** [comment]
It actually was the first time! I hadn't considered that it may have something to do with it.

**Comment by IdrisQe** [comment]
Huh... Thinking maybe the issue arose from config generation, I deleted all my configs (admittedly after switching some other mods out for testing purposes) and the error didn't occur again...

However, I just deleted all my configs again (more mod switching around, pretty sure I haven't re-added anything that I previously removed), and this time the error re-occured, but once again only on the first launch afterward.

**Comment by Fuzss** [comment]
I can't reproduce the issue, so I could only try to make some minor changes.

v1.3 containing those changes is now live on CurseForge, feel free to check it out and reopen this ticket if the issue resurfaces.
