### ISSUE TITLE
[Suggestion] Fix for Curse of Binding and keepInventory

### ISSUE THREAD

**Issue by IdrisQe** [Fuzss/sneakycurses#4]
I feel like this kind of thing would fit with the mod's theme of improving enchants.

Currently, if you have keepInventory set to true (having different , and accidentally equip a Curse of Binding item, that item will be stuck on you... until it breaks, even if you die. With anything that has a higher durability, this is an absolute pain.

It'd be neat to have an option to make it so items bound to you can be removed in some way... Two ways I'm thinking are:
1. Equip a Curse of Vanishing item alongside. When you die, items with Curse of Binding will still drop even with keepInventory on
2. Probably outside the scope but maybe some complicated way to remove curses so you aren't stuck with an item equipped in Hardcore, for example... Not sure what...
After all... If you get a Diamond Chestplate from a chest that's bound to you, you're basically screwed in Hardcore in the End without access to Elytras from End Ships (yeah Enderpearls but in Hardcore that's super risky)

**Comment by Fuzss** [comment]
Hmm, Curse of Binding and `keepInventory` together really are a problem. Have to say though that no suggestion really strikes me as rather intuitive, and that's what I'd like the solution to be.

Also I'd prefer if suggestions were kept on CurseForge. Feel free to repost your suggestion over there.
