### ISSUE TITLE
SneakyMagic crashes when loaded together with VillagerGuards

### ISSUE THREAD

**Issue by Patrigan** [Fuzss/sneakycurses#5]
Reason it crashes is because VillagerGuards is loading items from loottables and SneakyMagic tries to apply looting to it, which it shouldn't.

Simple fix would be to have a null check on the damage source (when calling the looting event).
see:
https://gist.github.com/ShootToKillSTK/f3464ca4c523412df16017dbb50900c3

**Comment by Fuzss** [comment]
Fixed in v.1.3.1.

**Comment by Patrigan** [comment]
Out of curiosity, because I might want to steal the idea (totally different purpose) how did you fix it? :o

**Comment by Fuzss** [comment]
https://github.com/Fuzss/sneakymagic/blob/b0ce6bc593cbb6324c12bed7f35a41aabd771fd4/src/main/java/com/fuzs/sneakymagic/element/CompatibilityElement.java#L155
